version: '3.8'

services:
  flask_app:
    build:
      context: .  # Diretório atual
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mapeia a porta 5000 do container para a máquina local
    volumes:
      - .:/app  # Monta o diretório local no container
    environment:
      - FLASK_ENV=development  # Configura o ambiente para desenvolvimento
      - MQTT_BROKER=BrokerEstacao  # Nome do serviço Mosquitto como variáveis de ambiente
    command: python app.py  # Executa a aplicação
  
  mosquitto:
    image: eclipse-mosquitto:latest  # Imagem oficial do Mosquitto
    container_name: mosquitto-broker  # Nome do contêiner
    ports:
      - "1883:1883"  # Porta MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf  # Arquivo de configuração personalizado
      - ./data:/mosquitto/data  # Persistência de dados
      - ./log:/mosquitto/log  # Persistência de logs
    restart: always  # Sempre reiniciar o container em caso de falha
