version: '3.8'

services:
  flask_app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    volumes:
      - .:/app  
    environment:
      - FLASK_ENV=development  
      - MQTT_BROKER=BrokerEstacao  
    command: python app.py  

  mysql:
    image: mysql:8.0  
    container_name: mysql-database  
    environment:
      MYSQL_ROOT_PASSWORD: example  # Senha root do MySQL
      MYSQL_DATABASE: weather_data  # Nome do banco de dados
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  # Persistência de dados
      - ./tabela.sql:/docker-entrypoint-initdb.d/tabela.sql  # Script para criar a tabela

  mosquitto:
    image: eclipse-mosquitto:latest  # Imagem oficial do Mosquitto
    container_name: mosquitto-broker  # Nome do container
    ports:
      - "1883:1883"  # Porta MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf  # Configuração do Mosquitto
      - ./data:/mosquitto/data  # Persistência de dados
      - ./log:/mosquitto/log  # Persistência de logs
    restart: always  # Reiniciar automaticamente

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminN 
    environment:
      PMA_HOST: mysql  # Nome do serviço MySQL no Docker Compose
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example  # Deve ser igual ao configurado no MySQL
    ports:
      - "8000:80"  # Porta para acessar o phpMyAdmin no navegador
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local  # Volume para persistência do banco de dados
